config/routes.rb
Rails.application.routes.draw do
  resources :solvability_cons
  resources :solvability_pros
  resources :solvability_pros
  resources :problem_comments
  resources :problems
  resources :causalities
  resources :solvabilities
  resources :events do resources :solvabilities end # nested resources
  resources :events do resources :causalities end # nested resources
  devise_for :users
  get 'welcome/index'
  put 'causality/_form'

  root 'welcome#index'

end

app/models/solvability_con.rb
class SolvabilityCon < ActiveRecord::Base
  belongs_to :solvability
  belongs_to :user
end

app/controllers/solvability_cons_controller.rb
class SolvabilityConsController < ApplicationController
  before_action :set_solvability_con, only: [:show, :edit, :update, :destroy]

  # GET /solvability_cons
  # GET /solvability_cons.json
  def index
    @solvability_cons = SolvabilityCon.all
  end

  # GET /solvability_cons/1
  # GET /solvability_cons/1.json
  def show
  end

  # GET /solvability_cons/new
  def new
    @solvability_con = SolvabilityCon.new
  end

  # GET /solvability_cons/1/edit
  def edit
  end

  # POST /solvability_cons
  # POST /solvability_cons.json
  def create
    @solvability_con = SolvabilityCon.new(solvability_con_params)

    respond_to do |format|
      if @solvability_con.save
        format.html { redirect_to @solvability_con, notice: 'Solvability con was successfully created.' }
        format.json { render :show, status: :created, location: @solvability_con }
      else
        format.html { render :new }
        format.json { render json: @solvability_con.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solvability_cons/1
  # PATCH/PUT /solvability_cons/1.json
  def update
    respond_to do |format|
      if @solvability_con.update(solvability_con_params)
        format.html { redirect_to @solvability_con, notice: 'Solvability con was successfully updated.' }
        format.json { render :show, status: :ok, location: @solvability_con }
      else
        format.html { render :edit }
        format.json { render json: @solvability_con.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solvability_cons/1
  # DELETE /solvability_cons/1.json
  def destroy
    @solvability_con.destroy
    respond_to do |format|
      format.html { redirect_to solvability_cons_url, notice: 'Solvability con was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solvability_con
      @solvability_con = SolvabilityCon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solvability_con_params
      params.require(:solvability_con).permit(:solvability_id, :user_id)
    end
end

app/helpers/solvability_cons_helper.rb
module SolvabilityConsHelper
end

app/views/solvability_cons/_form.html.erb
<%= form_for(@solvability_con) do |f| %>
  <% if @solvability_con.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solvability_con.errors.count, "error") %> prohibited this solvability_con from being saved:</h2>

      <ul>
      <% @solvability_con.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :solvability_id %><br>
    <%= f.number_field :solvability_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solvability_cons/edit.html.erb
<h1>Editing Solvability Con</h1>

<%= render 'form' %>

<%= link_to 'Show', @solvability_con %> |
<%= link_to 'Back', solvability_cons_path %>

app/views/solvability_cons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Solvability Cons</h1>

<table>
  <thead>
    <tr>
      <th>Solvability</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solvability_cons.each do |solvability_con| %>
      <tr>
        <td><%= solvability_con.solvability_id %></td>
        <td><%= solvability_con.user_id %></td>
        <td><%= link_to 'Show', solvability_con %></td>
        <td><%= link_to 'Edit', edit_solvability_con_path(solvability_con) %></td>
        <td><%= link_to 'Destroy', solvability_con, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solvability con', new_solvability_con_path %>

app/views/solvability_cons/new.html.erb
<h1>New Solvability Con</h1>

<%= render 'form' %>

<%= link_to 'Back', solvability_cons_path %>

app/views/solvability_cons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Solvability:</strong>
  <%= @solvability_con.solvability_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @solvability_con.user_id %>
</p>

<%= link_to 'Edit', edit_solvability_con_path(@solvability_con) %> |
<%= link_to 'Back', solvability_cons_path %>