config/routes.rb
Rails.application.routes.draw do
  resources :solvability_cons
  resources :solvability_pros
  resources :solvability_pros
  resources :problem_comments
  resources :problems
  resources :causalities
  resources :solvabilities
  resources :events do resources :solvabilities end # nested resources
  resources :events do resources :causalities end # nested resources
  devise_for :users
  get 'welcome/index'
  put 'causality/_form'

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  # Benefits  : [current event] ---solve--> [Related event]
  has_many :s2d_solvabilities, class_name: "Solvability", foreign_key: :src_id, :dependent => :destroy
  has_many :benefits,  through: :s2d_solvabilities

  # Solutions : [current event] <--solve--- [Related event]
  has_many :d2s_solvabilities, class_name: "Solvability", foreign_key: :dst_id, :dependent => :destroy
  has_many :solutions, through: :d2s_solvabilities

  # Risks     : [Current Event] ---cause--> [Related event]
  has_many :s2d_causalities,   class_name: "Causality",   foreign_key: :src_id, :dependent => :destroy
  has_many :risks,     through: :s2d_causalities

  # Causes    : [current event] <--cause--- [Related event]
  has_many :d2s_causalities,   class_name: "Causality",   foreign_key: :dst_id, :dependent => :destroy
  has_many :causes,    through: :d2s_causalities

  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :user_id, :user)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t :list_event_title %></h1>
<br />
<%= t :event_comment %><br />
<%= t :event_comment2 %><br />
<br />
<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th colspan="2">Title</th>
      <th>User</th>
    </tr>
    <tr>
      <th colspan="4">Content</th>
    </tr>
    <tr>
      <th width=150>Benefits</th>
      <th width=150>Solutions</th>
      <th width=150>Risks</th>
      <th width=150>Causes</th>
    </tr>
    
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr><td></td><td></td><td></td><td></td></tr>
      <tr>
        <td><%= event.id %></td>
        <td colspan="2"><%= event.title %></td>
        <td><%= event.user.email %></td>
        <td><%= link_to 'Show', event %></td>
       </tr>
       <tr>
        <td colspan="4"><%= event.content %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
       <tr>
        <td>
         	<% if event.benefits.each do |benefit| %>
         	  <%= link_to benefit.title, benefit %>
         	  <br/>
         	<% end.empty? %>
         	  <font color="RED">None</font>
         	<% end %>
        </td>
        <td>
         	<% if event.solutions.each do |solution| %>
         	  <%= link_to solution.title, solution %>
         	  <br/>
         	<% end.empty? %>
         	  <font color="RED">None</font>
         	<% end %>
        </td>
        <td>
         	<% if event.risks.each do |risk| %>
         	  <%= link_to risk.title, risk %>
         	  <br/>
         	<% end.empty? %>
         	  <font color="RED">None</font>
         	<% end %>
        </td>
        <td>
         	<% if event.causes.each do |cause| %>
         	  <%= link_to cause.title, cause %>
         	  <br/>
         	<% end.empty? %>
         	  <font color="RED">None</font>
         	<% end %>
        </td>
       </tr>
       <tr>
        <td align="center"><%= button_to 'Add Benefit',  new_event_solvability_path(event), params: {direction: 'src'}, method: :get %></td>
        <td align="center"><%= button_to 'Add Solution', new_event_solvability_path(event), params: {direction: 'dst'}, method: :get %></td>
        <td align="center"><%= button_to 'Add Risk',  new_event_causality_path(event), params: {direction: 'src'}, method: :get %></td>
        <td align="center"><%= button_to 'Add Cause', new_event_causality_path(event), params: {direction: 'dst'}, method: :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th colspan="2">Title</th>
      <th>User</th>
    </tr>
    <tr>
      <th colspan="4">Content</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @event.id %></td>
        <td colspan="2"><%= @event.title %></td>
        <td><%= @event.user.email %></td>
        <td><%= link_to 'Show', @event %></td>
       </tr>
       <tr>
        <td colspan="4"><%= @event.content %></td>
        <td><%= link_to 'Edit', edit_event_path(@event) %></td>
        <td><%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
  </tbody>
</table>
<br/>

<p class="relations">	Benefits: 
<% if @event.benefits.each do |benefit| %>
  <%= link_to benefit.title, benefit %>
<% end.empty? %>
  <font color="RED">None</font>
<% end %>
<%= button_to 'Add Benefit',  new_event_solvability_path(@event), params: {direction: 'src'}, method: :get %>
</p>

<p class="relations">Solutions:       
<% if @event.solutions.each do |solution| %>
  <%= link_to solution.title, solution %>
<% end.empty? %>
  <font color="RED">None</font>
<% end %>
<%= button_to 'Add Solution', new_event_solvability_path(@event), params: {direction: 'dst'}, method: :get %>
</p>

<p class="relations">Risks:     
<% if @event.risks.each do |risk| %>
  <%= link_to risk.title, risk %>
<% end.empty? %>
  <font color="RED">None</font>
<% end %>
<%= button_to 'Add Risk',  new_event_causality_path(@event), params: {direction: 'src'}, method: :get %>
</p>

<p class="relations">Causes:
<% if @event.causes.each do |cause| %>
  <%= link_to cause.title, cause %>
<% end.empty? %>
  <font color="RED">None</font>
<% end %>
<%= button_to 'Add Cause',  new_event_causality_path(@event), params: {direction: 'dst'}, method: :get %>
</p>         	
         	
<br/>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', :back %>