config/routes.rb
Rails.application.routes.draw do
  resources :solvability_cons
  resources :solvability_pros
  resources :solvability_pros
  resources :problem_comments
  resources :problems
  resources :causalities
  resources :solvabilities
  resources :events do resources :solvabilities end # nested resources
  resources :events do resources :causalities end # nested resources
  devise_for :users
  get 'welcome/index'
  put 'causality/_form'

  root 'welcome#index'

end

app/models/problem_comment.rb
class ProblemComment < ActiveRecord::Base
  belongs_to :problem
end

app/controllers/problem_comments_controller.rb
class ProblemCommentsController < ApplicationController
  before_action :set_problem_comment, only: [:show, :edit, :update, :destroy]

  # GET /problem_comments
  # GET /problem_comments.json
  def index
    @problem_comments = ProblemComment.all
  end

  # GET /problem_comments/1
  # GET /problem_comments/1.json
  def show
  end

  # GET /problem_comments/new
  def new
    @problem_comment = ProblemComment.new
  end
  
  # GET /problem_comments/new/1
  def new_id
    @problem_comment = ProblemComment.new
    @problem = Problem.find(params[:id])
  end

  # GET /problem_comments/1/edit
  def edit
  end

  # POST /problem_comments
  # POST /problem_comments.json
  def create
    @problem_comment = ProblemComment.new(problem_comment_params)

    respond_to do |format|
      if @problem_comment.save
        format.html { redirect_to @problem_comment, notice: 'Problem comment was successfully created.' }
        format.json { render :show, status: :created, location: @problem_comment }
      else
        format.html { render :new }
        format.json { render json: @problem_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problem_comments/1
  # PATCH/PUT /problem_comments/1.json
  def update
    respond_to do |format|
      if @problem_comment.update(problem_comment_params)
        format.html { redirect_to @problem_comment, notice: 'Problem comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem_comment }
      else
        format.html { render :edit }
        format.json { render json: @problem_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_comments/1
  # DELETE /problem_comments/1.json
  def destroy
    @problem_comment.destroy
    respond_to do |format|
      format.html { redirect_to problem_comments_url, notice: 'Problem comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem_comment
      @problem_comment = ProblemComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_comment_params
      params.require(:problem_comment).permit(:problem_id, :content)
    end
end

app/helpers/problem_comments_helper.rb
module ProblemCommentsHelper
end

app/views/problem_comments/_form.html.erb
<%= form_for(@problem_comment) do |f| %>
  <% if @problem_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem_comment.errors.count, "error") %> prohibited this problem_comment from being saved:</h2>

      <ul>
      <% @problem_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.number_field :problem_id %>
  </div>  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problem_comments/_formid.html.erb
<%= form_for(@problem_comment) do |f| %>
  <% if @problem_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem_comment.errors.count, "error") %> prohibited this problem_comment from being saved:</h2>

      <ul>
      <% @problem_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>  
  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.number_field :problem_id, value: (@problem.id) %>
  </div>  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problem_comments/edit.html.erb
<h1>Editing Problem Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem_comment %> |
<%= link_to 'Back', problem_comments_path %>

app/views/problem_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Problem Comments</h1>

<table>
  <thead>
    <tr>
      <th>Problem</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @events = Event.all %>

  <tbody>
    <% @problem_comments.each do |problem_comment| %>
      <tr>
        <td><%= @events.where(id: problem_comment.problem_id)[0].title %></td>
        <td><%= problem_comment.content %></td>
        <td><%= link_to 'Show', problem_comment %></td>
        <td><%= link_to 'Edit', edit_problem_comment_path(problem_comment) %></td>
        <td><%= link_to 'Destroy', problem_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem comment', new_problem_comment_path %>

app/views/problem_comments/new.html.erb
<h1>New Problem Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', problem_comments_path %>

app/views/problem_comments/new_id.html.erb
<p id="notice"><%= notice %></p>

<h1>New Problem Comment</h1>

<%= render 'formid' %>

<%= link_to 'Back', problems_show_comments_path(@problem) %>

app/views/problem_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @problem_comment.problem_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @problem_comment.content %>
</p>

<% @problem = Problem.all %>
<% @problem = @problem.where(id: @problem_comment.problem_id) %>

<%= link_to 'Edit', edit_problem_comment_path(@problem_comment) %> |
<%= link_to 'Back', problems_show_comments_path(@problem_comment.problem_id) %>