config/routes.rb
Rails.application.routes.draw do
  resources :solvability_cons
  resources :solvability_pros
  resources :solvability_pros
  resources :problem_comments
  resources :problems
  resources :causalities
  resources :solvabilities
  resources :events do resources :solvabilities end # nested resources
  resources :events do resources :causalities end # nested resources
  devise_for :users
  get 'welcome/index'
  put 'causality/_form'

  root 'welcome#index'

end

app/models/solvability_pro.rb
class SolvabilityPro < ActiveRecord::Base
  belongs_to :solvability
  belongs_to :user
end

app/controllers/solvability_pros_controller.rb
class SolvabilityProsController < ApplicationController
  before_action :set_solvability_pro, only: [:show, :edit, :update, :destroy]

  # GET /solvability_pros
  # GET /solvability_pros.json
  def index
    @solvability_pros = SolvabilityPro.all
  end

  # GET /solvability_pros/1
  # GET /solvability_pros/1.json
  def show
  end

  # GET /solvability_pros/new
  def new
    @solvability_pro = SolvabilityPro.new
  end

  # GET /solvability_pros/1/edit
  def edit
  end

  # POST /solvability_pros
  # POST /solvability_pros.json
  def create
    @solvability_pro = SolvabilityPro.new(solvability_pro_params)

    respond_to do |format|
      if @solvability_pro.save
        format.html { redirect_to @solvability_pro, notice: 'Solvability pro was successfully created.' }
        format.json { render :show, status: :created, location: @solvability_pro }
      else
        format.html { render :new }
        format.json { render json: @solvability_pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solvability_pros/1
  # PATCH/PUT /solvability_pros/1.json
  def update
    respond_to do |format|
      if @solvability_pro.update(solvability_pro_params)
        format.html { redirect_to @solvability_pro, notice: 'Solvability pro was successfully updated.' }
        format.json { render :show, status: :ok, location: @solvability_pro }
      else
        format.html { render :edit }
        format.json { render json: @solvability_pro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solvability_pros/1
  # DELETE /solvability_pros/1.json
  def destroy
    @solvability_pro.destroy
    respond_to do |format|
      format.html { redirect_to solvability_pros_url, notice: 'Solvability pro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solvability_pro
      @solvability_pro = SolvabilityPro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solvability_pro_params
      params.require(:solvability_pro).permit(:solvability_id, :user_id)
    end
end

app/helpers/solvability_pros_helper.rb
module SolvabilityProsHelper
end

app/views/solvability_pros/_form.html.erb
<%= form_for(@solvability_pro) do |f| %>
  <% if @solvability_pro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solvability_pro.errors.count, "error") %> prohibited this solvability_pro from being saved:</h2>

      <ul>
      <% @solvability_pro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :solvability_id %><br>
    <%= f.number_field :solvability_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solvability_pros/edit.html.erb
<h1>Editing Solvability Pro</h1>

<%= render 'form' %>

<%= link_to 'Show', @solvability_pro %> |
<%= link_to 'Back', solvability_pros_path %>

app/views/solvability_pros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Solvability Pros</h1>

<table>
  <thead>
    <tr>
      <th>Solvability</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solvability_pros.each do |solvability_pro| %>
      <tr>
        <td><%= solvability_pro.solvability_id %></td>
        <td><%= solvability_pro.user_id %></td>
        <td><%= link_to 'Show', solvability_pro %></td>
        <td><%= link_to 'Edit', edit_solvability_pro_path(solvability_pro) %></td>
        <td><%= link_to 'Destroy', solvability_pro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solvability pro', new_solvability_pro_path %>

app/views/solvability_pros/new.html.erb
<h1>New Solvability Pro</h1>

<%= render 'form' %>

<%= link_to 'Back', solvability_pros_path %>

app/views/solvability_pros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Solvability:</strong>
  <%= @solvability_pro.solvability_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @solvability_pro.user_id %>
</p>

<%= link_to 'Edit', edit_solvability_pro_path(@solvability_pro) %> |
<%= link_to 'Back', solvability_pros_path %>